services:
  notebook:
    image: quay.io/jupyter/pytorch-notebook
    volumes:
      - ./src/:/home/jovyan
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: ""
      JUPYTER_PASSWORD: ""
    command: start-notebook.py --NotebookApp.token='' --NotebookApp.password=''
